### ISSUE TITLE
Furigana in input

### ISSUE THREAD

**Issue by Shou-nen** [nihongodera/limelight#11]
Is it possible to add furigana in input text to help the algorithm understand what is correct kana or simply force specific kana for a given kanji (especially when convert to romaji)?

Something like
漢字 [かんじ] or [漢字] {かな} etc.

**Comment by zachleigh** [comment]
Hello Shou-nen. No, this is currently not possible. It is possible to add custom dictionaries to Mecab, the underlying tokenizer that Limelight uses. (I don't know how to do that so you'll have to figure that one out yourself.) That might solve your issue.
