### ISSUE TITLE
Kanji -> Furigana translation sometimes makes small mistakes

### ISSUE THREAD

**Issue by Oxbobby** [nihongodera/limelight#13]
Hello :)

First of all, congratulations on the great work this plugin is.

Second, I wanted to ask - maybe this is because of a dictionary error, not because of the plugin, but sometimes I get wrongly translated furigana when translating from kanji. Given how difficult it is to write it 100% correctly, I guess so, but I was wondering if there's a way to fix those inconsistencies?

For example, I've found this small errors:

土 - get's translated as ど while it should be つち
一人 - get's translated as　いちにん while it should be　ひとり 
三百 - get's translated as　さんひゃく while it should be さんびゃく
...

This is to show an example of a few, there are more, although I would say about 95% of the translated text is correct... which is absolutely awesome.

By any chance, do you have any suggestions for the above predicament?

**Comment by zachleigh** [comment]
Hello @borislav-itskov 
Yeah, most of those issues are problems with Mecab itself. You can test this by running Mecab in the command line.
```
$mecab
土
土	名詞,一般,*,*,*,*,土,ド,ド
EOS

一人
一	名詞,数,*,*,*,*,一,イチ,イチ
人	名詞,接尾,助数詞,*,*,*,人,ニン,ニン
EOS

三百
三	名詞,数,*,*,*,*,三,サン,サン
百	名詞,数,*,*,*,*,百,ヒャク,ヒャク
EOS
```
I think you can fix some of these issues by adding a custom dictionary to Mecab. I have never done this myself, but maybe this will be of help? https://towardsdatascience.com/mecab-usage-and-add-user-dictionary-to-mecab-9ee58966fc6
