### ISSUE TITLE
Composer namespace Limelight not found!

### ISSUE THREAD

**Issue by jun-dev** [nihongodera/limelight#9]
Not work for me. Composer not found your namespace and classname. Install is correct. Please help me for this.

My file installed.json:
`[
    {
        "name": "nihongodera/limelight",
        "version": "v1.6.6",
        "version_normalized": "1.6.6.0",
        "source": {
            "type": "git",
            "url": "https://github.com/nihongodera/limelight.git",
            "reference": "037cd19aa1df6ceb51b346af25378ee96de42a14"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/nihongodera/limelight/zipball/037cd19aa1df6ceb51b346af25378ee96de42a14",
            "reference": "037cd19aa1df6ceb51b346af25378ee96de42a14",
            "shasum": ""
        },
        "require": {
            "ext-mecab": "*",
            "php": ">=5.6"
        },
        "require-dev": {
            "phpunit/phpunit": "^6.4"
        },
        "time": "2018-09-22T02:16:06+00:00",
        "type": "project",
        "installation-source": "dist",
        "autoload": {
            "psr-4": {
                "Limelight\\": "src/"
            }
        },
        "notification-url": "https://packagist.org/downloads/",
        "license": [
            "MIT"
        ],
        "authors": [
            {
                "name": "Zach Leigh",
                "email": "zachleigh@fastmail.jp",
                "role": "Developer"
            }
        ],
        "description": "A php Japanese language text analyzer and parser.",
        "homepage": "https://github.com/nihongodera/limelight",
        "keywords": [
            "furigana",
            "japanese",
            "kanji",
            "language",
            "mecab",
            "parse",
            "romaji"
        ]
    },
    {
        "name": "overtrue/pinyin",
        "version": "3.0.6",
        "version_normalized": "3.0.6.0",
        "source": {
            "type": "git",
            "url": "https://github.com/overtrue/pinyin.git",
            "reference": "3b781d267197b74752daa32814d3a2cf5d140779"
        },
        "dist": {
            "type": "zip",
            "url": "https://api.github.com/repos/overtrue/pinyin/zipball/3b781d267197b74752daa32814d3a2cf5d140779",
            "reference": "3b781d267197b74752daa32814d3a2cf5d140779",
            "shasum": ""
        },
        "require": {
            "php": ">=5.3"
        },
        "require-dev": {
            "phpunit/phpunit": "~4.8"
        },
        "time": "2017-07-10T07:20:01+00:00",
        "type": "library",
        "installation-source": "dist",
        "autoload": {
            "psr-4": {
                "Overtrue\\Pinyin\\": "src/"
            }
        },
        "notification-url": "https://packagist.org/downloads/",
        "license": [
            "MIT"
        ],
        "authors": [
            {
                "name": "Carlos",
                "homepage": "http://github.com/overtrue"
            }
        ],
        "description": "Chinese to pinyin translator.",
        "homepage": "https://github.com/overtrue/pinyin",
        "keywords": [
            "Chinese",
            "Pinyin",
            "cn2pinyin"
        ]
    }
]
`
Any ideas?

**Comment by zachleigh** [comment]
Is it listed in your vendor/composer/autoload_classmap.php file? If not, try running `composer dumpautoload` to rebuild the class map.
